### ISSUE TITLE
E-mail Text for manually imported hospitals from medis-vs-covid19

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#100]
Einrichtungen die sich bei mvc19 gemeldet haben können manuell eingegeben werden. Beim Anlegen durch uns erhalten sie eine onboarding Mail. Hierfür muss noch Text geliefert werden und dann in die Mail eingebaut werden.

@maltezacharias und @andreaskind besorgen den Text und posten ihn hier für Johnny sobald er eingebaut werden kann

**Comment by josauder** [comment]
not needed anymore, hospitals have to sign themselves up with the regular workflow
