### ISSUE TITLE
Studierenden Registrierung Text zu Haftungsausschluss

### ISSUE THREAD

**Issue by andreaskind** [Baschdl/match4healthcare#106]
Vor den Registrierungsbutton soll noch folgender Text wegen der Haftung:

Die Vermittlung erfolgt unentgeltlich. Mir ist bewusst, dass die Ausgestaltung des Verhältnisses zur zu vermittelnden Institution allein mich und die entsprechende Institution betrifft. Insbesondere Art und Umfang der Arbeit, eine etwaige Vergütung und vergleichbares betreffen nur mich und die entsprechende Institution. Eine Haftung des Vermittlers ist ausgeschlossen.

**Comment by josauder** [comment]
Who is responsible for this? Have you talked to anybody?

**Comment by maltezacharias** [comment]
duplicate #97
