### ISSUE TITLE
Interaktion mit Website für Helfende

### ISSUE THREAD

**Issue by andyz02** [Baschdl/match4healthcare#115]
Wenn man sich als Helfende(r) registriert kommt man auf die "Danke" Seite und bekommt einen Bestätigungslink per E-Mail.

Die Helfenden haben keine Möglichkeit, mit der Website oder mit Kliniken zu interagieren. Das finde ich sehr schade. Die Helfenden sollten genauso wie die Kliniken automatisch angemeldet sein um die Website Weiternutzen zu können. So wäre doch eine Map mit allen Kliniken sehr interessant, damit der Helfende sieht, wo Hilfe gebraucht wird. Genauso könnte man dem Helfenden die Option geben, Kliniken (nur direkt auf der Website) zu kontaktieren. Die Klinik kann dann über ein Dashboard diese anfragen sehen und den Helfenden ggf. kontaktieren.

Es wäre gut, wenn der Helfer irgendwie mit der website interagieren könnte. So ist es grad ein bisschen "langweilig" und wenig spannend für den helfenden...

**Comment by josauder** [comment]
This issue is not directly measureable. While I agree with the sentiment, there is no clearly defined requirement for this right now. I will close this issue - feel free to clarify requirements for behaviour with @maltezacharias
