### ISSUE TITLE
Mail an Studierende nach Registrierung

### ISSUE THREAD

**Issue by andreaskind** [Baschdl/match4healthcare#118]
Text:

Liebe_r Helfende_r,

Vielen Dank für deine Anmeldung auf match4healthcare! Gemeinsam sind wir ein unschlagbares Team! :) Wir hoffen sehr, dass wir dich bald zu einem Platz zum helfen vermitteln können. 

Bitte validiere deine Registrierung, indem du auf den folgenden Link klickst:

Validierungslink.com

Hier einige wichtige Informationen zum allgemeinen Ablauf für dich:

- Im Falle eines Matches werden Gesundheitsinstitutionen dich kontaktieren und sich über Einzelheiten mit dir abstimmen. Die Kontaktaufnahme erfolgt außerhalb unserer Plattform.

- Wenn du dich bereits in einer andere Liste, z.b. der Unikliniken oder medizinischen Fakultäten eingetragen hast, denk daran, dass du Bescheid gibst, falls du über unsere Plattform einen Match erhältst und keine weiteren Kapazitäten mehr hast. Genauso andersherum, falls du über diese lokalen Wege helfen kannst, entferne deinen Eintrag bei uns. Wir wollen, dass für niemanden Verwirrung und doppelter Aufwand entsteht, sondern einzig und allein, dass du einen Ort zum Helfen findest, egal über welchen Weg.

- Wir informieren die Institutionen, dass Sie sich um einen Arbeitsvertrag sowie hygienische Standards und eine Einarbeitung kümmern sollten. Bitte achte darauf, dass du dich versichern lässt. Für weiteres siehe die Tipps und Infos zu Vertrag, Vergütung und Recht siehe [hier](Link zu der Seite "Rechtliche Fragen für Helfende").

- Sollte eine Institution Falschangaben gemacht haben oder sich nicht an die Grundbedingungen zu Ausrüstung/Versicherung halten, dann bitte informiere uns bitte über die u.g. E-Mail Adresse. 

- Wenn du Fragen zu lokalen Gegebenheiten oder Studienbedingungen hast, melde dich bei deiner lokalen Fachschaft Medizin oder lokalen Ärztekammer. Wir stellen dir hier nur Infos zusammen, aber können dir keine Fragen zu den genauen Bedingungen deines Einsatzes vor Ort beantworten, und für etwaige Probleme keine Haftung übernehmen. 

- Wenn du aufgrund deines Gesundheitszustands unsicher bist, ob du helfen darfst, hilft dir diese App weiter: https://covapp.charite.de/

In jedem Fall ein großes Dankeschön für deine freiwillige Unterstützung des Gesundheitswesens in der aktuellen Lage. Wir hoffen, mit dieser Plattform einen kleinen Beitrag zum Wohle der Gesellschaft geleistet zu haben.

Wenn du weitere Fragen hast wende dich gerne an info@match4healthcare.de

Dein match4healthcare Team

**Comment by josauder** [comment]
ach du je ist das lang, dann clicken die leute nicht auf den link

**Comment by Baschdl** [comment]
Duplicate to 157
