### ISSUE TITLE
Neue Verlinkung zu "Rechtliche Fragen für Helfende"

### ISSUE THREAD

**Issue by andreaskind** [Baschdl/match4healthcare#119]
Soll erst sichtbar sein, wenn man eingeloggt ist.

Text kommt noch:
https://docs.google.com/document/d/1Ab-l7wsWoCmuPWl1ppc1y3AhmgPVm6mFqyRBfdX_7TI/edit#

unter Rechtliche Fragen für Helfende bei der Coron Pandemie (WIP)

ist freigegeben sobald (WIP) entfernt wurde

**Comment by Baschdl** [comment]
Duplicate to #161 

Nur sichtbar, wenn eingeloggt ist aktuell nicht implementiert
