### ISSUE TITLE
Verwendung von "Vermittlung" prüfen, darf nirgends sein

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#131]
![image](https://user-images.githubusercontent.com/3034832/77599852-72849580-6f06-11ea-8865-bb8f9d46910a.png)

@andyz02: Das ist der Text den wir von @andreaskind bekommen haben. Habt ihr auch schon über die "Vermittlung" gesprochen?

**Comment by maltezacharias** [comment]
![image](https://user-images.githubusercontent.com/9914287/77633800-4988f280-6f50-11ea-9fd4-d9b84ff6871c.png)

**Comment by josauder** [comment]
![image](https://user-images.githubusercontent.com/12648328/77635732-4d6a4400-6f53-11ea-9706-ee69f381f55d.png)

**Comment by maltezacharias** [comment]
#154 @josauder

**Comment by Baschdl** [comment]
#153
