### ISSUE TITLE
Optimize loading speed of landing page (website)

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#152]
Check with [https://developers.google.com/speed/pagespeed/insights/?hl=de&url=http%3A%2F%2F40.68.80.151%2F](https://developers.google.com/speed/pagespeed/insights/?hl=de&url=http%3A%2F%2F40.68.80.151%2F) results in
<img width="752" alt="image" src="https://user-images.githubusercontent.com/3034832/77633101-43464680-6f4f-11ea-9bf6-5abb47513e85.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/3034832/77633138-4e00db80-6f4f-11ea-9f77-2e20cdaeda44.png">

**Comment by andyz02** [comment]
war nur mobil das problem. sollte jetzt behoben sein in neuer design-v3 :)
