### ISSUE TITLE
Mail an Institutionen nach Anmeldung

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#155]
child of #153

Sehr geehrte Einrichtung,

Vielen Dank für Ihren Eintrag auf match4healthcare! Wir hoffen sehr, dass Sie schnell und direkt die Hilfe finden, die Sie suchen. Hier haben wir Ihnen einige wichtige Informationen zusammengetragen. Dies soll Ihnen eine Hilfe sein, jedoch gewährleisten wir keinen Anspruch auf Vollständigkeit:

- Nachdem Ihre Registrierung und Verifizierung abgeschlossen ist, können Sie in der Datenbank nach Ihren Kriterien Helfende finden. Wir stellen Ihnen dann die Kontaktdaten der von Ihnen gewählten Helfenden zur Verfügung. Anschließend sind Sie selbstständig und unabhängig von unserer Plattform für die Kontaktaufnahme und Klärung der weiteren Details zuständig. 
- Wenn Sie Helfende nicht mehr benötigen, bitte geben Sie diesen Bescheid, damit diese Ihren Status bei uns anpassen können und für andere Einrichtungen zur Verfügung stehen. 
- Wir haben die Studierenden über Ihre Arbeitsrechte und Ausbildungsvertrag informiert. Bitte sorgen Sie sich um Rechtssicherheit und Versicherungsschutz der Helfenden. Ebenfalls muss geeignete Schutzausrüstung zur Verfügung gestellt und hygienische Standards eingehalten werden.
- Bitte überprüfen Sie vor Ort die Kompetenzen und ggf. erforderlichen formalen Qualifikationen der Helfenden. Besprechen Sie welche Befugnisse die Helfenden bei Ihnen haben und welche nicht. Sie sind für ihren Einsatz verantwortlich.
- Manche unserer Helfenden würden gerne an einem ferneren Einsatzort helfen, jedoch benötigen Sie dafür eine Unterkunft. Falls Sie diese unkompliziert anbieten können, so würden sich unsere Studierenden über die Unterstützung diesbezüglich sehr freuen. 

In jedem Fall ein großes Dankeschön für das große Engagement Ihrer Einrichtung in der aktuellen Lage. Wir hoffen, mit dieser Plattform einen kleinen Beitrag für die aktuelle Gesundheitsversorgung geleistet zu haben. 

Für Anregungen zu unserer Plattform und bei weiteren Fragen kontaktieren Sie uns gerne unter info@match4healthcare.de.

Ihr Team von match4healthcare

**Comment by Baschdl** [comment]
@josauder Kannst du das bei deinen Änderungen noch hinzufügen?

**Comment by josauder** [comment]
ist schon drin, in dem PR den bjarne reviewd
