### ISSUE TITLE
Strategy/error message for filtering page for logged in students

### ISSUE THREAD

**Issue by bjrne** [Baschdl/match4healthcare#159]
As a logged in student, I am redirected to a login form after clicking "Detailansicht" on helper map:
http://127.0.0.1:8000/accounts/login/?next=/ineedstudent/students/AT/2145/0

It is true that this view is not intended for students, what do we do? Hide link to "Detailansicht" for logged in students?

**Comment by maltezacharias** [comment]
Yes
