### ISSUE TITLE
Rechtliche Fragen für Helfende bei der Corona-Pandemie

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#161]
child of #153 
Please create a simple static page, url /rechtliche-fragen contant as follows:
see #157 

# Disclaimer
Wir fassen hier nach unserem besten Wissen und Gewissen Tipps und Fragestellungen zusammen, von denen wir denken, dass du sie vor deiner Tätigkeit als Helfende_r während der Corona Krise durchgehen solltest. Wir erheben keinen Anspruch auf die Vollständigkeit und Korrektheit dieser Zusammenfassung. match4healthcare übernimmt weder die Haftung noch etwaige notwendige Versicherungen für die Einsätze, die im Anschluss an ein Matching durch match4healthcare entstehen.

# Auf was müsst ihr beim Unterschreiben eines Vertrags achten?

## Einhaltung von Tarifverträgen:
In den Kliniken solltet ihr mindestens in die Tarifklasse TVÖD-P5 eingruppiert werden. Wenn ihr eine Berufsausbildung habt, dann entsprechend höher. Im anderen öffentlichen Einrichtungen sollt ihr euren Tätigkeiten entsprechend eingruppiert werden. Hier kommt es auf eure Tätigkeit an.

## Was ist, wenn ich schon einen anderen Job habe?
Ihr müsst selbstständig darauf achten, dass ihr alle eure Jobs bei der Institution, in der ihr arbeitet, angebt. Mögliche Pflichten zur Angabe weiterer Tätigkeiten bestehen auch während der Kurzarbeit weiter.
### Generelles:

- Am 23.03. hat Jens Spahn in der PK zur Novelle des Infektionsschutzgesetzes verkündet, dass Vergütung bei der Unterstützung in der Versorgung im Rahmen der aktuellen Situation nicht auf das Bafög angerechnet wird. Allerdings gibt es juristische Zweifel an der umfassenden Geltung dieser Regelung, so dass wir hoffen und davon ausgehen, dass es nicht angerechnet wird. Es gibt aktuell aber noch Unklarheiten. Bei Fragen wendet euch an das für euch zuständige Amt für Ausbildungsförderung.
- Ab einem Einkommen von 9.408€/Jahr seid ihr einkommenssteuerpflichtig. Beachtet, dass ihr ggf. für das gesamte Jahr rückwirkend Sozialversicherungsbeiträge zahlen müsst, wenn ihr über diese Grenze kommt.
- Unten geben wir einen kurzen Überblick über mögliche Anstellungsverhältnisse. Solltet ihr noch offene Fragen haben, findet ihr auf der Homepage eurer Krankenkasse alle Informationen über mögliche Regelungen und Einschränkungen. Zudem ändert der Gesetzgeber aktuell einige Regelungen im Rahmen der COVID-19 Pandemie, um die Tätigkeit bestmöglich zu unterstützen. Die bvmd und weitere Studierendenverbände berichten hierzu meist täglich. Klärt in diesem Zusammenhang bei Unklarheiten auch, ob euer Gehalt weiterhin bezahlt wird, falls ihr in Quarantäne müsst.
- Mit einer Anstellung gilt für euch das Arbeitszeit und Arbeitsschutzgesetz. Solltet ihr Verdacht haben, dass dies keine Berücksichtigung findet, sprecht dies offen und lösungsorientiert an. Zur Arbeitszeit können Ausnahmen ausgesprochen werden, falls dies für die Versorgung zwingend notwendig sein sollte. Lasst euch aber trotzdem nicht ausnutzen! Wendet euch bei Fragen an den Betriebsrat oder die Gewerkschaft (Marburger Bund).
- Für Schwangere und Stillende gilt das Mutterschutzgesetz. Untenstehende Ausführungen des Landes Baden-Württemberg empfehlen mit Stand vom 24.03.20 nur patientenferne Tätigkeiten sowie Tätigkeiten ohne vermehrten Personenkontakt. Aufgrund der schlechteren Schutzwirkung der FFP2/3 Masken bei Schwangeren sollten diese in keinen Tätigkeitsbereichen arbeiten, in denen diese Masken zur persönlichen Schutzausrüstung gehören. In Gebieten mit regionalen Epidemien ist von einer Beschäftigung komplett abzusehen. Euch steht in jedem Falle ein persönliches Gespräch mit dem Arbeitgeber zu, um die Möglichkeiten zu eruieren. Weitere Informationen:
https://rp.baden-wuerttemberg.de/Themen/Wirtschaft/Documents/Corona_Info_schwangere_Frauen.pdf

### Mögliche Anstellungsverhältnisse sind:

- Werkstudentenvertrag (nur Rentenversicherung)
Ihr dürft bis zu 20h/Woche arbeiten. In der vorlesungsfreien Zeit dürft ihr bis zu 40h/Woche arbeiten. Ob die Zeit aktuell als vorlesungsfrei gilt, müsst ihr mit euren Fakultäten vor Ort klären. Die Vorlesungszeit bleibt von Universitätsschließungen möglicherweise unberührt. Weitere Details hierzu bekommt ihr üblicherweise auch über euer Studierendenwerk. 

Im Mittel dürft ihr über das gesamte Jahr trotzdem maximal 20h/Woche arbeiten! Dies gilt für alle Beschäftigungsverhältnisse.

- **Geringfügige Beschäftigung**
Diese Anstellungsform ist nahezu immer möglich, auch wenn ihr schon einen anderen Job habt. Achtet hier darauf, dass ihr je nach Stundenlohn der anstellenden Institution nur relativ kurz im Monat zur Verfügung steht.
- **Kurzfristige Beschäftigung**
Ihr könnt bis zu 70 Tage im Jahr frei arbeiten und habt keine Einschränkungen beim monatlichen Umfang. Die 70 Tage können dabei auf mehrere Arbeitgeber aufgeteilt werden.
- **Festanstellung**
Mit einer Festanstellung seid ihr sozialversicherungspflichtig beschäftigt. Ihr zahlt Sozialabgaben und habt eine gewisse Anzahl an Stunden, die ihr ableisten müsst.
- **Übungsleiterpauschale**
Die Übungsleiterpauschale beträgt 3000€ und kann bei bestimmten Tätigkeiten in Vereinen, kirchlichen Einrichtungen und anderen Institutionen des öffentlichen Rechts in Anspruch genommen werden. Sie zählt dabei nicht zu deinem Gehalt und wirkt sich somit auch nicht auf Bafög, Steuern und Sozialversicherungspflicht aus. Eine solche Aufwandsentschädigung sollte für ehrenamtliche Unterstützung angenommen werden, nicht als Ersatz für eine berufliche Tätigkeit, auch wenn eure Einrichtung die entsprechenden Kriterien erfüllt. Die Grenze verläuft allerdings fließend.

## Famulatur/Pflegepraktikum (für Medizinstudierende):
Eine Famulatur muss in der vorlesungsfreien Zeit stattfinden und von einem Arzt/einer Ärztin bescheinigt werden. Viele Kliniken und Fakultäten haben hier aktuell Sonderregelungen, die das Ableisten einer Famulatur oder eines Pflegepraktikums ermöglichen. Die Details hierzu müsst ihr mit eurer jeweiligen Institution vor Ort besprechen. Es kann gegebenenfalls auch eine bezahlte Tätigkeit als Famulatur bescheinigt werden. Im aktuellen Gesetzesentwurf (Stand 25.03.2020) ändert auch das Bundesministerium für Gesundheit die Approbationsordnung für Ärzte Anfang April, um diesbezüglich Rechtssicherheit herzustellen.

**Comment by Baschdl** [comment]
Let's use /legal-questions
