### ISSUE TITLE
Hier sollte automatisch Österreich ausgewählt sein. Bei der "Profil" Seite ist es aber korrekt.

### ISSUE THREAD

**Issue by andyz02** [Baschdl/match4healthcare#165]
<img width="1141" alt="Screen Shot 2020-03-26 at 12 27 42 PM" src="https://user-images.githubusercontent.com/62519417/77641996-3cbecb80-6f5d-11ea-83ec-396579075781.png">

**Comment by josauder** [comment]
awaiting PR merge
