### ISSUE TITLE
anstatt Bezahlung lieber die Position reingeben, Arzt, medstudent usw

### ISSUE THREAD

**Issue by andyz02** [Baschdl/match4healthcare#167]
<img width="1180" alt="Screen Shot 2020-03-26 at 12 36 45 PM" src="https://user-images.githubusercontent.com/62519417/77642796-88be4000-6f5e-11ea-9c3e-e4b82b19092a.png">

**Comment by andyz02** [comment]
Oder falls möglich bei Bezahlung einfach ja/nein und dann zusätzlich noch die Berufsausbildung

**Comment by josauder** [comment]
Closing for now - please discuss form requirements with everybody on the med team and @maltezacharias
