### ISSUE TITLE
Add Thieme logo

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#177]
[https://match4healthcare.slack.com/archives/C010C97KYTA/p1585230672070800](https://match4healthcare.slack.com/archives/C010C97KYTA/p1585230672070800)

**Comment by bjrne** [comment]
Siehe auch: https://de.wikipedia.org/wiki/Datei:Thieme-Logo.svg

**Comment by andyz02** [comment]
done
