### ISSUE TITLE
Terms of usage Mapbox

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#19]
We use Mapbox to display the OSM map but are unsure about their terms of usage

**Comment by bjrne** [comment]
https://www.mapbox.com/pricing/#gltile
TLDR: 200k static tile requests are free, the following requests are billed with 0.50$/1000 tiles, resulting in 100$ for every 200k extra requests.

**Comment by Baschdl** [comment]
Asked for support as a community project

**Comment by josauder** [comment]
Moved to #102
