### ISSUE TITLE
(Studierende) Text für Passwort erstellen Seite nach Registrierung

### ISSUE THREAD

**Issue by andreaskind** [Baschdl/match4healthcare#190]
Überschrift:
- "Neues Passwort" entfernen
- "Erfolgreiche Anmeldung"

Liebe*r Helfende*r,

vielen Dank für deine Registrierung. Auf dieser Seite kannst du ein Passwort für deinen Account erstellen und dich damit einloggen.

**Comment by maltezacharias** [comment]
close merged to #222
