### ISSUE TITLE
(Studierende) Bei der Registrierung für Mediziner

### ISSUE THREAD

**Issue by andreaskind** [Baschdl/match4healthcare#191]
Den Punkt:
"Eine Anerkennung als Teil eines Studienabschnitts (Pflegepraktikum/Famulatur) ist wichtig"
Stilistisch durch (bspw. durch fett Markierung) von den anderen Antwortmöglichkeiten abheben.
Nicht wichtig für den Launch!!!

**Comment by maltezacharias** [comment]
closed by #222
