### ISSUE TITLE
Feedback & Bugs aus dem #feedback channel aus Slack bearbeiten

### ISSUE THREAD

**Issue by andreaskind** [Baschdl/match4healthcare#197]
Falls es Fragen zu den jeweiligen Bugs oder Feedbacks gibt, dann mit Andreas (K), Malte oder dem Postenden direkt besprechen.

**Comment by Baschdl** [comment]
![image](https://user-images.githubusercontent.com/3034832/77700101-d44f0900-6fb3-11ea-9463-993c0aa5a94a.png)
[https://en.wikipedia.org/wiki/SMART_criteria](https://en.wikipedia.org/wiki/SMART_criteria)

That would be nice :D An issue like this here doesn't add any value
