### ISSUE TITLE
(Hospital views student) Tabelle mit den restlichen spalten erweitern

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#20]
https://pypi.org/project/django-advanced-filters/

https://hackernoon.com/how-to-add-tags-to-your-models-in-django-django-packages-series-1-4y1b32sf

https://getbootstrap.com/docs/4.4/components/badge/

**Comment by maltezacharias** [comment]
Possible duplicate of #32 ?

**Comment by josauder** [comment]
this issue is obsolete with new table
