### ISSUE TITLE
Hinweistext für die Mail

### ISSUE THREAD

**Issue by andreaskind** [Baschdl/match4healthcare#287]
Text für das Mail Erstellungsfeld:

Bitte schreiben Sie in diese Mail an die Helfenden kurze Informationen zur geplanten Tätigkeit:
- zeitlicher Umfang, 
- Aufgabengebiet/Abteilung,
- Vergütung / Modalitäten
- Arbeitsvertrag / Versicherungsverhältnis

So können die Helfenden schneller sehen, ob diese Stelle zu Ihnen passt, sparen sich Nachfragen bei Ihnen und können zügiger zu- oder absagen.

**Comment by maltezacharias** [comment]
https://app.slack.com/client/T0100P155FD/C010K4T5YGZ/thread/C010K4T5YGZ-1585467062.004100
Text ist abgestimmt, bitte einbauen

**Comment by Baschdl** [comment]
Ich habe es jetzt zu dem Text gemacht: 
```
Bitte schreiben Sie in diese Mail an die Helfenden kurze Informationen zur geplanten Tätigkeit:

- zeitlicher Umfang,
- Aufgabengebiet/Abteilung,
- Vergütung / Modalitäten
- Arbeitsvertrag / Versicherungsverhältnis

So können die Helfenden schneller sehen, ob diese Stelle zu Ihnen passt, sparen sich Nachfragen bei Ihnen und können zügiger zu- oder absagen.

Liebe(r) Helfende(r),

Wir sind... 
Wir suchen...

Meldet euch baldmöglichst!

Beste Grüße,
Max Mustermann

Tel: 456789
Email: max.mustermann@tum.de
```
Oder soll es nur der in Slack diskutierte sein? Dann wären der Name, Telefonnummer und Email nicht dynamisch drin.

Aktuell könnte es aber passieren, dass sie den Text nicht rauslöschen. Ein check einbauen?

**Comment by maltezacharias** [comment]
Nach reiflichem Überlegen, bitte den Textvorschlag

> Der Text in diesem Feld wird an die Helfenden per Mail verschickt, nachdem wir Sie als Institution verifiziert haben:
> Bitte schreiben Sie in diese Mail an die Helfenden kurze Informationen zur geplanten Tätigkeit:
> - zeitlicher Umfang,
> - Aufgabengebiet/Abteilung,
> - Vergütung / Modalitäten
> - Arbeitsvertrag / Versicherungsverhältnis
> So können die Helfenden schneller sehen, ob diese Stelle zu Ihnen passt, sparen sich Nachfragen bei Ihnen und können zügiger  zu- oder absagen.

an der blau markierten Stelle einfügen als BootStrap Info:
```
<div class="alert alert-info" role="alert">
  This is a info alert—check it out!
</div>
```
![image](https://user-images.githubusercontent.com/9914287/80871880-ca08e480-8cae-11ea-9428-d86123f033c3.png)

**Comment by Baschdl** [comment]
Django forms does not provide for this: https://github.com/match4everyone/match4healthcare/blob/761248c27b49e568c545c643a72eac9a040649d7/backend/apps/iamstudent/forms.py#L530
@feeds Do you have an idea?

**Comment by bjrne** [comment]
I'm not sure I understand the problem, but we could initialize the form layout manually like here: https://github.com/match4everyone/match4healthcare/blob/761248c27b49e568c545c643a72eac9a040649d7/backend/apps/iamstudent/forms.py#L453

**Comment by Baschdl** [comment]
Yes, we have to use a manual layout
