### ISSUE TITLE
Mails without validation link

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#288]
![image](https://user-images.githubusercontent.com/3034832/77849717-f45a1480-71cd-11ea-8b4a-3404b5a4b503.png)

Actionable when Michael forwards me the mail

**Comment by kevihiiin** [comment]
Cannot reproduce the error, the link is there when you click on the pink text.
But it is weird, that the mail is not official sent via our domain, but displays "über sendgrid.net". Does not show the same when I recieve it.
Can the user forward the mail?

**Comment by maltezacharias** [comment]
@Baschdl wo steht das im Slack? Ich find den Thread nicht..

**Comment by maltezacharias** [comment]
Hab mit Michael per Screensharing drauf geschaut. Keine Ahnung warum Google den Link nicht rendert, war aber am Wochenende aus dem Testsystem und wenn ich jetzt ein neues Konto erstelle funktioniert es auch bei ihm. Wenn da was war ist das anscheinend erledigt. Trotzdem sollten wir den Link für alle Fälle ausgeschrieben als Text anzeigen. 

Dann kann man zur Not immer noch kopieren..
