### ISSUE TITLE
Email an Studierende

### ISSUE THREAD

**Issue by josauder** [Baschdl/match4healthcare#297]
Endpoint, den man als Admin rufen kann
- [x] Link unten in Krankennausemail zum Account deaktivieren
- [ ] Sucht alle user, die vor mehr als 3 Tagen eine email bekommen haben, denen schicken wir eine email "Hast du dich gematcht? wenn ja unsubscibe"
- [x] Limit Emails pro krankenhaus pro tag. "If you have a good reason to send more emails, wendet euch an support@match4healthcare.de"

solve #231 while at it

**Comment by feeds** [comment]
maybe make token inspired from https://simpleisbetterthancomplex.com/tutorial/2016/08/24/how-to-create-one-time-link.html

**Comment by feeds** [comment]
moved the first point of the issue into #309
