### ISSUE TITLE
Add Datenschutzerklärung

### ISSUE THREAD

**Issue by bjrne** [Baschdl/match4healthcare#30]
- [ ] create route
- [ ] link in Impressum
- [ ] Checkbox [read] in Forms, not Model

**Comment by andreaskind** [comment]
https://www.medis-vs-covid19.de/datenschutzerklaerung/

**Comment by andreaskind** [comment]
Wir werden eine Feedbackform über Typeform benutzen, das muss auch in die Datenschutzerklärung mit rein.

**Comment by Baschdl** [comment]
@andreaskind Wir schreibt das? Gibt's da etwas Vorgefertigtes?

**Comment by andreaskind** [comment]
Datenschutz­erklärung
Wer wir sind / Kontakt­information
Amandeep Grewal
Burgstraße 33
Reutlingen
Deutschland
Tel.: +49 7121 360 5434
E-Mail: info@medis-vs-covid19.de
Wir nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung.
Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder E-Mail-Adressen) erhoben werden, erfolgt dies stets auf freiwilliger Basis.
Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.
Für die Nutzung dieses Dienstes gilt folgendes:
Zweck der Datenerhebung ist die Vermittlung und Vernetzung von freiwilligen Hilfeleistungswilligen und Institutionen, die entsprechender Hilfe bedürfen.
 
Welche Daten zu welchem Zweck:
Helfende geben bei der Anmeldung auf der Plattform persönliche Daten an. Dabei werden der Vor- und Nachname, Wohnort, die E-Mail-Adresse und die Telefonnummer gespeichert. Zusätzlich geben die Helfenden an, welche Vorerfahrungen sie haben, in welchem Studienabschnitt sie sich befinden, ob eine Vergütung benötigt wird, wie viele Wochenarbeitsstunden sie arbeiten wollen, was ihr bevorzugter Einsatzort ist und ob an dem Einsatzort eine Unterkunft benötigt wird .
Sich anmeldende Einrichtungen geben den Namen der Einrichtung, den Namen der Ansprechperson, der Standort der Einrichtung. E-Mail-Adresse und Telefonnummer an. Diese werden ebenfalls gespeichert.
Zweck der Speicherung der Daten ist die Sicherstellung der Vermittlung von Helfenden an suchende Einrichtungen. Um den Kontakt herzustellen, erhalten die Einrichtungen Zugriff auf die Daten der Helfenden, hierbei werden jedoch keine Namen oder E-Mail Adressen ausgewiesen. Der E-Mail Kontakt von den Einrichtungen an die Helfenden verläuft zunächst über uns.
Welche Dauer:
Speicherdauer ist die Dauer des Vermittlungszeitraums. Sollte eine Vermittlung nicht mehr notwendig sein, werden die Daten gelöscht. Die genaue Dauer ist zum heutigen Zeitpunkt nicht abzusehen.
Wer hat Zugriff auf die Daten:
Alle angemeldeten Krankenhäuser und medizinischen Einrichtungen können auf die Daten zugreifen, damit die Vermittlung gewährleistet werden kann. Der Zugriff ist beschränkt auf Nutzer mit Zugangsdaten zum Account der angemeldeten Einrichtung.
Löschung der Daten:
Sollte eine Löschung der Daten gewünscht sein, kann dies per email an datenschutz@match4healthcare.de angezeigt werden.
Rechtsgrundlage:
Sie haben grundsätzlich folgende Rechte:
Auskunftsrecht (Art. 15 DSGVO)
Recht auf Berichtigung (Art. 16 DSGVO)
Widerspruchsrecht (Art. 21 DSGVO)
Recht auf Löschung (Art. 17 DSGVO)
Recht auf Einschränkung der Verarbeitung (Art. 18f. DSGVO)
Recht auf Datenübertragbarkeit (Art. 20 DSGVO)Recht auf Beschwerde bei einer Aufsichtsbehörde
Automatische Datenspeicherung
Wenn Sie heutzutage Webseiten besuchen, werden gewisse Informationen automatisch erstellt und gespeichert, so auch auf dieser Webseite.
Wenn Sie unsere Webseite so wie jetzt gerade besuchen, speichert unser Webserver (Computer auf dem diese Webseite gespeichert ist) automatisch Daten wie die IP-Adresse Ihres Gerätes, die Adressen der besuchten Unterseiten, Details zu Ihrem Browser (z.B. Chrome, Firefox, Edge,…) und Datum sowie Uhrzeit. Wir nutzen diese Daten nicht und geben Sie in der Regel nicht weiter, können jedoch nicht ausschließen, dass diese Daten beim Vorliegen von rechtswidrigem Verhalten eingesehen werden.
Cookies
Unsere Internetseite verwendet so genannte Cookies. Cookies richten auf Ihrem Rechner keinen Schaden an und enthalten keine Viren. Cookies dienen dazu, unser Angebot nutzerfreundlicher, effektiver und sicherer zu machen. Cookies sind kleine Textdateien, die auf Ihrem Rechner abgelegt werden und die Ihr Browser speichert.
Die meisten der von uns verwendeten Cookies sind so genannte „Session-Cookies“. Sie werden nach Ende Ihres Besuchs automatisch gelöscht. Andere Cookies bleiben auf Ihrem Endgerät gespeichert, bis Sie diese löschen. Diese Cookies ermöglichen es uns, Ihren Browser beim nächsten Besuch wiederzuerkennen.
Sie können Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und Cookies nur im Einzelfall erlauben, die Annahme von Cookies für bestimmte Fälle oder generell ausschließen sowie das automatische Löschen der Cookies beim Schließen des Browser aktivieren. Bei der Deaktivierung von Cookies kann die Funktionalität dieser Website eingeschränkt sein.
Wir verwenden auf dieser Webseite Google Analytics der Firma Google Inc. (1600 Amphitheatre Parkway Mountain View, CA 94043, USA) um Besucherdaten statistisch auszuwerten. Dabei verwendet Google Analytics zielorientierte Cookies.
Analysedienste
Datenschutzerklärung für die Nutzung von Google Analytics
Diese Website nutzt Funktionen des Webanalysedienstes Google Analytics. Anbieter ist die Google Inc. 1600 Amphitheatre Parkway Mountain View, CA 94043, USA. Google Analytics verwendet sog. „Cookies“. Das sind Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert.
Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt.
Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren: http://tools.google.com/dlpage/gaoptout?hl=de
Deaktivierung der Datenerfassung durch Google Analytics
Mithilfe des Browser-Add-ons zur Deaktivierung von Google Analytics-JavaScript (ga.js, analytics.js, dc.js) können Website-Besucher verhindern, dass Google Analytics ihre Daten verwendet.
Sie können die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem Sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren: https://tools.google.com/dlpage/gaoptout?hl=de
Server-Log-Files
Der Provider der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log Files, die Ihr Browser automatisch an uns übermittelt. Dies sind:
Browsertyp/ Browserversion
verwendetes Betriebssystem
Referrer URL
Hostname des zugreifenden Rechners
Uhrzeit der Serveranfrage
Diese Daten sind nicht bestimmten Personen zuordenbar. Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen. Wir behalten uns vor, diese Daten nachträglich zu prüfen, wenn uns konkrete Anhaltspunkte für eine rechtswidrige Nutzung bekannt werden.
Google Fonts Datenschutzerklärung
Wir verwenden Google Fonts der Firma Google Inc. (1600 Amphitheatre Parkway Mountain View, CA 94043, USA) auf unserer Webseite. Die Verwendung von Google Fonts erfolgt ohne Authentisierung und es werden keine Cookies and die Google Fonts API gesendet. Sollten Sie ein Konto bei Google haben, werden keine Ihrer Google-Kontodaten an Google während der Nutzung von Google Fonts übermittelt. Google erfasst lediglich die Nutzung von CSS und der verwendeten Fonts und speichert diese Daten sicher. Mehr zu diesen und weiteren Fragen finden Sie auf https://developers.google.com/fonts/faq.
Welche Daten von Google erfasst werden und wofür diese Daten verwendet werden, können Sie auf https://www.google.com/intl/de/policies/privacy/ nachlesen.
SSL-Verschlüsselung
Um Ihre übermittelten Daten bestmöglich zu schützen nutzen die Websitebetreiber eine SSL-Verschlüsselung. Sie erkennen derart verschlüsselte Verbindungen an dem Präfix “https://“im Seitenlink in der Adresszeile Ihres Browsers. Unverschlüsselte Seite sind durch „http://“gekennzeichnet.
Sämtliche Daten, welche Sie an diese Website übermitteln – etwa bei Anfragen oder Logins – können dank SSL-Verschlüsselung nicht von Dritten gelesen werden.
Eingebettete Inhalte von anderen Websites
Beiträge auf dieser Website können eingebettete Inhalte beinhalten (z. B. Videos, Bilder, Beiträge etc.). Eingebettete Inhalte von anderen Websites verhalten sich exakt so, als ob der Besucher die andere Website besucht hätte.
Diese Websites können Daten über Sie sammeln, Cookies benutzen, zusätzliche Tracking-Dienste von Dritten einbetten und Ihre Interaktion mit diesem eingebetteten Inhalt aufzeichnen, inklusive Ihrer Interaktion mit dem eingebetteten Inhalt, falls Sie ein Konto haben und auf dieser Website angemeldet sind.
Quelle: Teile dieser Datenschutzerklärung wurden mit dem Datenschutz Generator von firmenwebseiten.at erstellt.
