### ISSUE TITLE
Registrierungsseite Hospitals

### ISSUE THREAD

**Issue by andreaskind** [Baschdl/match4healthcare#318]
![2020-03-30 07 03 38](https://user-images.githubusercontent.com/14961544/77876961-b2c07c80-7254-11ea-95ca-9cbd732cf9ed.jpg)

Text "offizieller und Namen ihrer Institution" in "Offizieller Name Ihrer Institution" ändern

checkbox „auf der Karte sichtbar“ noch raus zu nehmen. 

Bisher verwirrt das den Klinikmenschen gerade nur, weil wir die Karte denen nicht erklärt haben. Außerdem müssen wir dafür nicht nach Erlaubnis fragen, solange die Mail eine öffentlich zugängliche ist (oder?).

**Comment by bjrne** [comment]
- [x] Change Label
- [ ] Checkbox "auf Karte anzeigen" rausnehmen
