### ISSUE TITLE
Add design hint that we have many columns in student details view

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#32]
It's not intuitively clear that we have many columns to view:

![image](https://user-images.githubusercontent.com/3034832/77427185-3fdb7f80-6dd6-11ea-8ac2-c9bff66ca0cf.png)

**Comment by maltezacharias** [comment]
@feeds versucht eine sinnvolle Lösung zu finden für die Ansicht und einen Teil der Filter auszulagern

**Comment by josauder** [comment]
issue obsolete with new table
