### ISSUE TITLE
Rechtschreibfehler korrigieren

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#321]
Andreas hat jemanden über die Seite proof-readen lassen, Korrekturen werden eingepflegt

**Comment by maltezacharias** [comment]
Mit Andreas abgesprochen, ist noch offen

[Der Glaube daran.docx](https://github.com/match4everyone/match4healthcare/files/4452361/Der.Glaube.daran.docx)

**Comment by Baschdl** [comment]
@maltezacharias @andyz02 Is this in process or done?
