### ISSUE TITLE
Remove 2nd jquery and bootscrapt js script tag

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#328]
Base.html now includes the jquery and bootstrap script tags twice. Remove latter instance and verify that it's not needed. Move all other script Tags to the header section, check for correct loading order

**Comment by bjrne** [comment]
Is this related to #295 @maltezacharias ? :)

**Comment by Baschdl** [comment]
We wouldn't necessary need the newer bootstrap version but I don't now if @andyz02 relies on it at some point. So I won't remove it for now.
