### ISSUE TITLE
Direct user to map view after login

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#34]

**Comment by josauder** [comment]
Ist das mit allen anderen abgeklärt? Eigentlich müsste ein studierender ja zur map von hospitals und ein hospital zur map von studierenden geleitet werden

**Comment by josauder** [comment]
@Baschdl what is expected behavior?

**Comment by bjrne** [comment]
Stays as it is for now

**Comment by josauder** [comment]
What is the status? What is desired behavior? I can help do this.
