### ISSUE TITLE
Setup Mail service

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#4]
A privately hosted mail server will probably be classified as spam by Gmail etc.

- [x] Find a mail service which we can use
- [x] Add configuration to settings/production.py **only on production server**

**Comment by Baschdl** [comment]
We will probably use sendgrid and see how far we can go with them

**Comment by maltezacharias** [comment]
duplicate of #49 or obsolete @Baschdl ?

**Comment by josauder** [comment]
@Baschdl Is this still an issue? If not, please close
