### ISSUE TITLE
Sie-Form auf den Passwort-Setzen-Seiten

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#435]
https://match4healthcare.slack.com/archives/C010K4T5YGZ/p1587019922015800

Auf der “Passwort setzen” Seite der Registrierungen, sollten wir lieber Sietzen anstatt weiter zu dutzen und “Liebe Vertrer*in einer Einrichtung,” oder sowas schreiben
Bisheriger Text
Liebe*r Helfer*in,
vielen Dank für deine Registrierung. Auf dieser Seite kannst du ein Passwort für deinen Account erstellen und dich damit einloggen.

**Comment by Baschdl** [comment]
Diese Seite sehen ja Helfer*innen und Vertrer*innen, dementsprechend würde ich etwas neutrales nehmen
