### ISSUE TITLE
Create new dev-Fixtures

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#465]
Create new fixtures for quick setup of dev systems
Include sample users and the following validated and approved users with username = password and e-mails set to something random:

- supporter
- facility
- staff
- superuser

**Comment by feeds** [comment]
if i am correct, staff == superuser at the moment

**Comment by feeds** [comment]
Look what I found, I guess creating a[ 'manage.py' command](https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/) is what we were looking for
