### ISSUE TITLE
Draft a proposal for a coherent code structuring approach within the project

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#468]
Should we use just one app? What should be in one app, what in another?
Should we create one app and what sub-structure should we create inside?
Should we use e.g. only class based views, how should we group our classes?

Take a look at sucessful django projects and how they handle this? Keep in mind that a best-practice seemingly does not exist. I'd rather have a proposal that works for us and where we know where to expect a file. Take a look at what we implemendted so far and verify that the proposal defines a clear location for all code that we wrote

**Comment by feeds** [comment]
One conclusion: We have A LOT of logic that should go into the models instead of the views

**Comment by feeds** [comment]
@kevihiiin I will do a proposal for a first step in that direction by 
- [ ] separating all models into files
- [ ] using class based views as suggested on most websites
- [ ] organizing the templates

**Comment by feeds** [comment]
This is solved by creating m4e I guess...

**Comment by maltezacharias** [comment]
agreed
