### ISSUE TITLE
Adjust wording for hospital perspective

### ISSUE THREAD

**Issue by bjrne** [Baschdl/match4healthcare#474]
![Screenshot from 2020-05-03 12-37-12](https://user-images.githubusercontent.com/7229585/80912142-3e896500-8d3b-11ea-87c1-b058d4801df6.png)

- [ ] "Nur Studierende: [..]": eher "die Stelle kann als Pflegepraktikum/Famulatur angerechnet werden"
- [x] "Verfügbar ab" klingt als ob die Stelle ab da verfügbar, aber nicht fest benötigt. Der filter schmeißt aber alle raus, die erst später können, auch wenn das nur wenige Tage sind. Idealerweise ein min-max, wie bei Ausblidungsabschnitt ungefähr?

**Comment by kevihiiin** [comment]
Mir sind auch noch zwei Dinge aufgefallen:
"Benötigt Vergütung"
- [wissen wir nicht] zeigt alle an
- [ja] zeigt auch alle an
- [nein] zeigt nur die an die keine Vergütung benötigen (also auch welche die "nein darf nicht" ausgewählt haben)
- [individuell absprechbar] zeigt nur die an die "nein darf nicht" gewählt haben

=> Könnte man die Frage in "Können Vergütung anbieten" umbenennen und dann die Option "individuell absprechbar" entfernen, da die Vergütung sowieso individuell abgesprochen wird? Zusätzlich könnten der wir sagen bei "ja" fliegen einfach die raus die "nein darf nicht bezahlt werden" ausgewählt haben.

"Kann eine Unterkunft angeboten werden"
- [wissen wir nicht] alle
- [ja] zeigt nur die an die eine Unterkunft brauchen
- [nein] zeigt nur die an die keine Unterkunft brauchen

=> In der Frage steht ja "kann", sollten bei [ja] nicht auch alle angezeigt werden?

**Comment by feeds** [comment]
![image](https://user-images.githubusercontent.com/8030048/82667584-6bdd7a80-9c38-11ea-9a5e-327c9bb7aedf.png)

**Comment by feeds** [comment]
[wir können zwar ...] => alle helfenden werden angezeigt
[helfende müssen] => nur die die vergütung wollen und die denen es egal ist
[wir können keine...] => nur die die keine wollen und die denen es egal ist

[ist möglich] => alle
[nein] => nur die die keine brauchen

**Comment by feeds** [comment]
@maltezacharias ich seh das eine häckchen nicht (müsste unter pflegepraktikum sein)
![image](https://user-images.githubusercontent.com/8030048/82668079-4dc44a00-9c39-11ea-8577-279f26e997df.png)
