### ISSUE TITLE
Twitter and Facebook logo not shown on match4healthcare.de with ad blocker

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#481]
with Adblock Plus

**Comment by bjrne** [comment]
with ublock origin on firefox, ubuntu it is working

**Comment by kevihiiin** [comment]
Under Manjaro (Linux) with 
+ Vivaldi + Ublock origin
+ Chrome + Adblock plus
+ Firefox + Adblock plus

it is also working

**Comment by Baschdl** [comment]
Can't reproduce it right know
