### ISSUE TITLE
Create github action for code style checking

### ISSUE THREAD

**Issue by bjrne** [Baschdl/match4healthcare#488]
Depends on #486

**Comment by Baschdl** [comment]
What should be the output of such an action? Pass/Fail or a report in a PR?

**Comment by bjrne** [comment]
additional check for PRs, pass/fail. We could additionally think about a report of a code-style metric or maximum complexity. flake8 already supports this, I just haven't activated it yet.

**Comment by Baschdl** [comment]
Ok, you should be able to implement this similar to https://github.com/match4everyone/match4healthcare/blob/414752d2bff966567ea16be78bbc68cf090e2d05/.github/workflows/tests.yml#L52

**Comment by bjrne** [comment]
Was merged in #502
