### ISSUE TITLE
Rate limit Django-Slack logger

### ISSUE THREAD

**Issue by kevihiiin** [Baschdl/match4healthcare#498]
**Is your feature request related to a problem? Please describe.**
When our application gets brute force attacks under different subdomains (wrong request headers), we get a lot of Slack messages

**Describe the solution you'd like**
Rate limit the slack logger

**Describe alternatives you've considered**
+ Exclude these log entries from the slack-bot and log to file only
+ Use Fail2Ban and write custom jail for our specific log file

**Additional context**
https://github.com/wkeeling/ratelimitingfilter/blob/master/ratelimitingfilter/ratelimitingfilter.py

**Comment by Baschdl** [comment]
@maltezacharias fixed this specific error with nginx. Do we still wanna rate limit the logger?

**Comment by kevihiiin** [comment]
I think handling it in nginx is the most elegant solution. If someone is actually trying to target us via header injection the requests will still go through and we there will be errors in the log file (which is good!)

**Comment by Baschdl** [comment]
👍 So we are closing this one?

**Comment by kevihiiin** [comment]
In favour :smile:
