### ISSUE TITLE
Login workflow: after signing up you should see your own data

### ISSUE THREAD

**Issue by josauder** [Baschdl/match4healthcare#50]
if e.g. a hospital signs up, it should not be taken to a new empty signup form when pressing "i need help" but instead should edit its own, already submitted data

**Comment by Baschdl** [comment]
I would suggest:

if logged_in and is_hospital:
     Link zeigt zu /accounts/profile_hospital
else:
     Link zeigt zu /accounts/signup_hospital

**Comment by Baschdl** [comment]
Could be done for launch but no priority

**Comment by maltezacharias** [comment]
Same for Students, agreed to @Baschdl, not launch priority;

**Students**
```
if logged_in and is_hospital:
      Link zeigt zu /accounts/profile_student
else:
      Link zeigt zu /accounts/signup_student
```

**Hospitals**
```
if logged_in and is_hospital:
      Link zeigt zu /accounts/profile_hospital
else:
      Link zeigt zu /accounts/signup_hospital
```

**Comment by bjrne** [comment]
After talking to Malte, this also includes setting sensible visibility settings for items in navbar, namely:
Logged in students get about, map, account
logged in hospitals get about, iNeedHelp, map, account
where iNeedHelp redirects to filtering page

**Comment by bjrne** [comment]
I am failing to redirect to the specific page for the hospital. The following snippets works when added into base.html:
```html
{% if user.is_authenticated and user.is_hospital %}
{% url 'send_mail_student_id_list' user.hospital.plz as filter_student_url %}
{% if filter_student_url %}
    <a href="{{ filter_student_url }}">Just a test to check wether filter_student_url is created and exists</a>
{% endif %}
<li class="nav-item  {% if "signup_hospital" in request.path %}active{% endif %} hide-home">
    <a class="nav-link" href="{{ filter_student_url }}">{% blocktrans %}Ich brauche
        Hilfe{% endblocktrans %}</a>
</li>
{% endif %}
```
but exchanged with the following line, it does not create the url variable:
`{% url 'list_by_plz' user.hospital.countrycode user.hospital.plz as filter_student_url %}`
