### ISSUE TITLE
black and flake8 have conflicting rules for blank lines after the docstring

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#518]
`backend/apps/ineedstudent/converters.py:2:1: D205 1 blank line required between summary line and description`

@kevihiiin that was your problem

**Comment by bjrne** [comment]
Can you give an example @Baschdl? I fixed the problem flake8 was mentioning in a following commit.

**Comment by Baschdl** [comment]
This fix interestingly didn't work for me but it's fine if it's green now

**Comment by bjrne** [comment]
Then I guess you forgot to stage the changes from black and it seemed that black changed something again, when it only operated on the staged changes thus creating the same unstaged change again, resulting in seemingly the same errors and changes. Will close for now.
