### ISSUE TITLE
mind the gap (unter der website)

### ISSUE THREAD

**Issue by feeds** [Baschdl/match4healthcare#55]
What about that nav bar

**Comment by maltezacharias** [comment]
Sollte behoben sein mit Andreas Layoutänderungen.. @feeds  was ist genau gemeint?

**Comment by josauder** [comment]
![image](https://user-images.githubusercontent.com/12648328/77582268-6b965c80-6edf-11ea-8150-4e9faee19ea5.png)

Dieser hässliche Platz zwischen map und footer nehme ich an. Stand aktueller `staging`

**Comment by maltezacharias** [comment]
#95 sollte das beheben.. PR abwarten

**Comment by maltezacharias** [comment]
verified: PR #95 behebt den Bug, in staging reproduzierbar, design-v3 fixt das

**Comment by maltezacharias** [comment]
Linked to PR, will close automatically
