### ISSUE TITLE
Hässlicher Fehler: uniqueness of mail in edit profile, falls email in der db schon existiert (feeds), bug mit hospital edit

### ISSUE THREAD

**Issue by feeds** [Baschdl/match4healthcare#56]

**Comment by maltezacharias** [comment]
Mein Vorschlag wäre die e-Mail einfach nicht änderbar machen, müsste man dann eh neu validieren und alles. Wäre das ein quick-fix?

**Comment by josauder** [comment]
Email editing was removed, this closes this issue
