### ISSUE TITLE
Student Form fertig stellen die texte

### ISSUE THREAD

**Issue by feeds** [Baschdl/match4healthcare#58]
- [x] Richtige Texte,
- [x] validate dass datenschutz und einwilligung = True sind
- [x] layout von Optionen als Medizinstudierender besser gestalten, Annerkennungscheckbox vom Rest separieren (siehe screenshot unten)

**Comment by bjrne** [comment]
![Screenshot from 2020-03-25 01-38-09](https://user-images.githubusercontent.com/7229585/77492884-f294f780-6e41-11ea-9b41-9ac1ecdd3d03.png)

**Comment by bjrne** [comment]
Layout obsolet durch Verwendung von Ampel
