### ISSUE TITLE
Benchmark site

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#6]
Possible tools:
- [Apache ab](http://httpd.apache.org/docs/2.4/programs/ab.html)
- [Apache JMeter](https://jmeter.apache.org/)

**Comment by maltezacharias** [comment]
@maltezacharias SSH Account auf gut angebundenem Server bereitstellen

**Comment by josauder** [comment]
This issue is not measurable. I will close it now. Reopen with specific benchmark requirements
