### ISSUE TITLE
Add favicons with alpha values 

### ISSUE THREAD

**Issue by bjrne** [Baschdl/match4healthcare#62]
![Screenshot from 2020-03-25 02-27-17](https://user-images.githubusercontent.com/7229585/77492213-3b4bb100-6e40-11ea-88d4-75d10d89e269.png)

**Comment by maltezacharias** [comment]
Bjrne: Das sollte schon erledigt gewesen sein, check mal bitte staging, wenn das immer noch da ist, sag mir nochmal Bescheid!
