### ISSUE TITLE
ValueError thrown when username and password are the same in hospital signup

### ISSUE THREAD

**Issue by kevihiiin** [Baschdl/match4healthcare#66]
When signing up for a hospital and the email / username and password are the same, a Value error is thrown:
```
ValueError at /accounts/signup_hospital
The User could not be changed because the data didn't validate.
```
Possible reason: The backend (middleware?) detects the weak password and the form does not validate and throws an error.
Possible fix: Catch in frontend & more precise error handling?

**Comment by Baschdl** [comment]
Could be done for launch but no priority

**Comment by josauder** [comment]
This is intended behaviour, for security and shit
