### ISSUE TITLE
Update about page

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#7]
Add all involved people: https://match4healthcare.slack.com/archives/C010C97KYTA/p1584992386032300 with pictures: https://drive.google.com/drive/folders/1-M7_lIZ7-iZtp-x8bs38LtNZOCAiYJHq

Rescale (and compress) pictures

`backend/templates/about.html`

**Comment by bjrne** [comment]
Closed in `79a014a`
