### ISSUE TITLE
Error on profile edit page

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#86]
`/accounts/profile_hospital`throws following error:

`backend     | KeyError: "Key 'email' not found in 'HospitalFormEditProfile'. Choices are: ansprechpartner, countrycode, firmenname, is_approved, plz, sonstige_infos, telefon."`

**Comment by maltezacharias** [comment]
@Baschdl Reiner Backend Error? Also nicht zwingend für Launch?
