### ISSUE TITLE
Update imprint

### ISSUE THREAD

**Issue by Baschdl** [Baschdl/match4healthcare#9]
Questions to clarify:
Who is responsible?

`backend/templates/impressum.html`

**Comment by maltezacharias** [comment]
Für den Anfang werden wir in den Imprint wohl eine GmbH von Andreas Zehetner nehmen, das ist auch noch eine der brennenden Rechtsfragen, müsste auf Slack als Andreas sein

**Comment by bjrne** [comment]
Ist erstmal mit eurem Impressum geupdated

**Comment by maltezacharias** [comment]
Es fehlen noch:
Link für die e-Mail Adresse (Bei Personen hinter diesem Projekt)
Link auf Datenschutzerklärung (Unsere Datenschutzerklärung finden Sie hier.), dort Link auf die Datenschutzerklärung.

blocked by #30

**Comment by josauder** [comment]
Done
