### ISSUE TITLE
Needs discussion:

### ISSUE THREAD

**Issue by feeds** [Baschdl/match4healthcare#90]
"Kranknhauskarte für anzeigen aktivieren"
=> alte anzeigen von der website können eingepflegt werden, die krankenhäuser verwalten sie, indem wir ihnen nen link schicken
=> neue krankenhäuse können auch von nich registrierten studis kontaktiert werden
=> anzeige kann selbstständig heruntergenommen werden wenn bedarf gedeckt ist

REquirements:
- Anmeldebutton students auf der map hinzufügen
- hospital model so ändern, dass sie eine anzeige stellen können

**Comment by Baschdl** [comment]
Duplicate to #92
