### ISSUE TITLE
hospital online anzeigen

### ISSUE THREAD

**Issue by feeds** [Baschdl/match4healthcare#92]
"Kranknhauskarte für anzeigen aktivieren"
=> alte anzeigen von der website können eingepflegt werden, die krankenhäuser verwalten sie, indem wir ihnen nen link schicken
=> neue krankenhäuse können auch von nich registrierten studis kontaktiert werden
=> anzeige kann selbstständig heruntergenommen werden wenn bedarf gedeckt ist

REquirements:

    Anmeldebutton students auf der map hinzufügen
    hospital model so ändern, dass sie eine anzeige stellen können
- hinzufügen im model:
  - anzeigetext
  - text soll angezeigt werden

- hinzufügen auf der mapview hospitals:
  - button "i'm a student sign me up" damit leute die direkt drauf landen sich auch registrieren
  - plz such esollte drinnen bleiben
  - in ineedstudent hospital_view den anzeigenzext anzeigen
  - im hospital by plz view die wuery nur auf Hospital.objects.filter(should_be_showed=True) ausführen (statt all())

**Comment by maltezacharias** [comment]
TS mit @josauder

**Comment by maltezacharias** [comment]
@josauder Wir blenden die Seite für den Launch aus damit wirs mit den Stakeholdern wirklich zementieren können, was der Workflow ist.

**Comment by josauder** [comment]
karte bleibt ausgeblendet + krankenhäuser von MedisVsCovid19 sollen sich selber eintragen
