### ISSUE TITLE
Mandatory Fehlermeldung forms nicht lokalisiert

### ISSUE THREAD

**Issue by andyz02** [Baschdl/match4healthcare#94]

**Comment by Baschdl** [comment]
@maltezacharias Duplicate to #8?

**Comment by maltezacharias** [comment]
War ein Artefakt beim Testen, Browser war auf Englisch, daher englische Meldung aber die Seite größtenteils auf Deutsch weil die Übersetzungen fehlen

**Comment by Baschdl** [comment]
Die fehlen auch, wenn ihr davor nicht `compilemessages` ausführt
