### ISSUE TITLE
Beschriftungsänderungen Student Onboarding Form

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#97]
**Umkreis:**
- [x] Statt 5, 10, 20, >20 km => 10 20 40 >40km

**Wunscheinsatzort:**

- [x] Arztpraxis => Arztpraxis/Ordination/MVZ
- [x] Krankeneinrichtungen => Klinikum/Spital
- [x] Gesundheitsamt => Gesundheitsamt und sonstige Einrichtungen

**Zeitliche Verfügbarkeit**

- [x] Beschriftungsfeld ändern in "Zeitliche Verfügbarkeit, bis zu"

**Qualifikationen:**

- [x] Notfallsanitäter_in/Rettungssanitäter_in => Notfallsanitäter_in/Rettungsassistent_in
- [x] Physiotherapeut_in => Physiotherapieauszubildende_r

**Datenschutz**
- [x] Bei der Checkbox Hiermit akzeptiere ich die Datenschutzbedingungen.
müsste noch ein Link dazu, der auf die Datenschutzbedingungen geht, target sollte ein neues Fenster sein

**Validierung**
![image](https://user-images.githubusercontent.com/9914287/77562995-ffa4fb80-6ec0-11ea-941c-05dae0eb000b.png)
Beschriftungen fehlen hier oder sind nicht korrekt. Wenn das hier nicht reinpasst, bitte beachten, weiteres Issue dazu existiert schon #63

**Comment by maltezacharias** [comment]
**Ergänzung:** #98 hier mit einbauen:
Vor dem Registriere mich Button ein div mit einer Klasse registration_disclaimer und dort folgenden Text:

"Bitte achte bei deinem Einsatz auf einen ausreichenden Versicherungsschutz und einen geregelten Arbeitsvertrag. Sollte eine Gesundheitseinrichtung dir dies nicht anbieten, so gehe kein unsicheres Arbeitsverhältnis ein, um dich selbst zu schützen."

**Comment by maltezacharias** [comment]
Andreas hat gerade folgenden Text geliefert, wenn möglich den nehmen:

Die Vermittlung erfolgt unentgeltlich. Mir ist bewusst, dass die Ausgestaltung des Verhältnisses zur zu vermittelnden Institution allein mich und die entsprechende Institution betrifft. Insbesondere Art und Umfang der Arbeit, eine etwaige Vergütung und vergleichbares betreffen nur mich und die entsprechende Institution. Eine Haftung des Vermittlers ist ausgeschlossen.

**Comment by Baschdl** [comment]
@andyz02 Hier wird "Vermittlung" verwendet
