### ISSUE TITLE
Field Changes Student Registration Form

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#99]
**Wunscheinsatzort**

Soll erweitert werden um:
- Apotheke (melde dich auch bei [#ApothekenHelfen](http://apothekenhelfen.bphd.de/))
- Ich helfe dort, wo ich kann
Bei den Apotheken Link ähnlich wie schon bei Qualifikation Pflege auf Pflegereserve
**Vor allem das letzte ist Mission Critical, weil das mehr umfasst als nur alle Optionen davor**

**Vor Vergütung, bzw. im selben Block**
- Ich benötige eine Unterkunft
Checkbox oder Drop-Down mit Ja/Nein, bei der Vergütung haben wir das absichtlicht der Texte wegen nicht als Check-Box gelöst, hier ist egal, was schneller geht. @maltezacharias sagt checkbox reicht.

** Kinderbetreuer_in**
Ist im Moment Checkboxen, wenn möglich bitte Umstellen wie bei allen anderen davor, mit der ButtonGroup:
Keine Angabe | Lediglich Erfahrungen |Abgeschlossene Ausbildung

**Comment by maltezacharias** [comment]
@bjrne Bitte auch das verfügbar ab auf das Tagesdatum initialisieren

**Comment by feeds** [comment]
@bjrne ich zeig dir wie man die kinderbrtreuer umstellt
